--running query 
create table PurchaseOrder as
with cte1 as
(
select ph.DOC_NO,ph.DOC_TOTAL,ph.SUBTOTAL,ph.SHIPTO_SUBC,ph.C_SUBTOTALNET,ph.PRIORITY,ph.SHIP_DATE,ph.SUBTOTALNET,ph.DUE_DATE,ph.COMPANYNO,ph.SUBC,ph.SHIPTO,ph.ACCTNO,ph.C_SUBTOTAL,ph.DISC_AMT,ph.SHIPVIA,ph.TERM_CODE,ph.ENTER_DATE,ph.DOC_DATE,ph.SHIP_COMPLETE,ph.PRINTED_DATE,ph.DOC_CATEGORY,ph.DOC_TYPE,ph.CCODE,ph.SHIPTO_CCODE,ph.USER_DOC,ph.DOC_STATUS,ph.POST_GL_DATE,pl.ADDED_DTE,pl.ALT2,pl.COND,pl.C_DOC_TOTAL,pl.NO_CHARGE,pl.SOURCE_PRICE,pl.CATEGORY,pl.CONV_DOC_CATEGORY,pl.LSTATUS,pl.SMAN3_AMT,pl.C_UNITP,pl.LINE_TYPE,pl.DESCRIPTN,pl.CONV_DOC,pl.UNITP_UM,pl.STATUS,pl.MFG_SUBC,pl.C_SMAN4_AMT,pl.LINE,pl.PARTNUMBER,pl.QTY_UM,pl.UNITP,pl.ALT1,pl.UPDATED_DTE,pl.CANCELED,pl.CONV_LN,pl.NOCHARGE,pl.QORDER,pl.QSHIP,pl.SUBP,pl.SOURCE_PRICE_VALUE,pl.CUST_PN,pl.PARTSERIAL,pl.MFG,pl.PART_SSN,pl.SERIAL_NO
from adp_po_hdr ph
join adp_po_line pl
on ph.doc_no=pl.doc_no
),
cte2 as
(select pl.ADDED_DTE,pl.SUBC,pl.UPDATED_DTE,pl.ACCTNO,pl.DOC_NO,pl.ALT2,pl.COND,pl.C_DOC_TOTAL,pl.NO_CHARGE,pl.SOURCE_PRICE,pl.CATEGORY,pl.CONV_DOC_CATEGORY,pl.LSTATUS,pl.SUBTOTALNET,pl.SHIPTO,pl.SMAN3_AMT,pl.C_UNITP,pl.LINE_TYPE,pl.DESCRIPTN,pl.CONV_DOC,pl.DOC_TOTAL,pl.UNITP_UM,pl.STATUS,pl.MFG_SUBC,pl.PRIORITY,pl.C_SMAN4_AMT,pl.LINE,pl.PARTNUMBER,pl.QTY_UM,pl.UNITP,pl.ALT1,pl.CANCELED,pl.DUE_DATE,pl.CONV_LN,pl.COMPANYNO,pl.NOCHARGE,pl.QORDER,pl.C_SUBTOTAL,pl.SUBTOTAL,pl.QSHIP,pl.SUBP,pl.C_SUBTOTALNET,pl.SOURCE_PRICE_VALUE,pl.CUST_PN,pl.PARTSERIAL,pl.MFG,pl.SHIP_DATE,pl.PART_SSN,pl.SERIAL_NO,pl.SHIPTO_SUBC,s2.ADR2,s2.ZIP,s2.STATE,s2.TEL1,s2.REGION,s2.SHIP_NO,s2.NAME,s2.CITY,s2.SHIP_TYPE,s2.TEL1_EXT,s2.ADR3,s2.ISACTIVE,s2.CCODE,s2.COUNTRY,s2.COUNTY,s2.TEL_PFIX,s2.FAX1,s2.ADR1
from adp_po_line pl
join adp_shipto s2
on pl.acctno=s2.acctno and pl.subc=s2.subc
where s2.ship_type ='S'
)

select cte1.DOC_NO,cte1.ALT2,cte1.ADDED_DTE,cte1.COND,cte1.C_DOC_TOTAL,cte1.NO_CHARGE,cte1.SOURCE_PRICE,cte1.CATEGORY,cte1.CONV_DOC_CATEGORY,cte1.LSTATUS,cte1.SUBTOTALNET,cte1.SUBC,cte1.SHIPTO,cte1.SMAN3_AMT,cte1.C_UNITP,cte1.LINE_TYPE,cte1.DESCRIPTN,cte1.CCODE,cte1.ACCTNO,cte1.DOC_TOTAL,cte1.CONV_DOC,cte1.UNITP_UM,cte1.STATUS,cte1.MFG_SUBC,cte1.PRIORITY,cte1.C_SMAN4_AMT,cte1.LINE,cte1.PARTNUMBER,cte1.QTY_UM,cte1.UNITP,cte1.ALT1,cte1.UPDATED_DTE,cte1.CANCELED,cte1.DUE_DATE,cte1.COMPANYNO,cte1.CONV_LN,cte1.NOCHARGE,cte1.C_SUBTOTAL,cte1.QORDER,cte1.SUBTOTAL,cte1.QSHIP,cte1.C_SUBTOTALNET,cte1.SUBP,cte1.SOURCE_PRICE_VALUE,cte1.CUST_PN,cte1.PARTSERIAL,cte1.MFG,cte1.SHIP_DATE,cte1.PART_SSN,cte1.SERIAL_NO,cte1.SHIPTO_SUBC,cte1.DISC_AMT,cte1.SHIPVIA,cte1.TERM_CODE,cte1.ENTER_DATE,cte1.DOC_DATE,cte1.SHIP_COMPLETE,cte1.PRINTED_DATE,cte1.DOC_CATEGORY,cte1.DOC_TYPE,cte1.SHIPTO_CCODE,cte1.USER_DOC,cte1.DOC_STATUS,cte1.POST_GL_DATE,cte2.ADR2,cte2.ZIP,cte2.STATE,cte2.TEL1,cte2.SHIP_NO,cte2.NAME,cte2.CITY,cte2.SHIP_TYPE,cte2.TEL1_EXT,cte2.ADR3,cte2.ISACTIVE,cte2.COUNTRY,cte2.COUNTY,cte2.TEL_PFIX,cte2.FAX1,cte2.REGION,cte2.ADR1
from cte1
join cte2
on cte1.doc_no=cte2.doc_no;
